bug fixes

diff --git a/deploy-new-arch b/deploy-new-arch
--- a/deploy-new-arch
+++ b/deploy-new-arch
@@ -3,6 +3,12 @@
 # USAGE
 # ./deploy-new-arch <spack defined architecture>
 
+existing_jobs=$(squeue -p building | wc -l)
+if [ "$existing_jobs" -gt "1" ]; then
+    echo "Operations under progress, unable to continue"
+    exit 1
+fi
+
 NEW_ARCH=$1
 
 if grep -Fxq "${NEW_ARCH}" spack-arch-list; then
diff --git a/install-package b/install-package
--- a/install-package
+++ b/install-package
@@ -3,15 +3,25 @@
 # USAGE
 # ./install-package <spack package spec>
 
+existing_jobs=$(squeue -p building | wc -l)
+if [ "$existing_jobs" -gt "1" ]; then
+    echo "Operations under progress, unable to continue"
+    exit 1
+fi
+
 SPACK_PACKAGE_NAME=$1
 
 IFS=$'\n' read -d '' -r -a lines < spack-arch-list
 
 for i in "${lines[@]}"
 do
-    echo "Starting job for architecture $i..."
-    sbatch --job-name="build-${SPACK_PACKAGE_NAME}" --constraint=$i --output=logs/$SPACK_PACKAGE_NAME-$i-%j.out --export=SPACK_PACKAGE_NAME=$SPACK_PACKAGE_NAME slurm-install-batch.sh
+    echo "Queuing job for architecture $i..."
+
+    sbatch --job-name="build-${SPACK_PACKAGE_NAME}" --constraint=$i --output=logs/$SPACK_PACKAGE_NAME-$i-%j.out --export=SPACK_PACKAGE_NAME=$SPACK_PACKAGE_NAME --dependency=singleton slurm-install-batch.sh
 done
 
 # add to package file if not already there
-grep -qxF '${SPACK_PACKAGE_NAME}' installed_packages || echo '${SPACK_PACKAGE_NAME}' >> installed_packages
+grep -qxF $SPACK_PACKAGE_NAME installed_packages || echo $SPACK_PACKAGE_NAME >> installed_packages
+
+# finished submitting jobs
+echo "Remember to run spack gc afterwards to remove excess build dependencies"
diff --git a/remove-package b/remove-package
--- a/remove-package
+++ b/remove-package
@@ -3,6 +3,12 @@
 # USAGE
 # ./remove-package <spack package spec>
 
+existing_jobs=$(squeue -p building | wc -l)
+if [ "$existing_jobs" -gt "1" ]; then
+    echo "Operations under progress, unable to continue"
+    exit 1
+fi
+
 SPACK_PACKAGE_NAME=$1
 
 # uninstall all specs assicated with package name
@@ -10,4 +16,4 @@ spack uninstall -a $SPACK_PACKAGE_NAME
 spack -y gc
 
 # remove line from installed_packages
-sed '/${SPACK_PACKAGE_NAME}/d' ./installed_packages
+sed -i "/$SPACK_PACKAGE_NAME/d" ./installed_packages
